import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`container mx-auto max-w-6xl relative antialiased`}>
        <header className="sticky top-0 z-[999] bg-[#ebebeb]">
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
